### ISSUE TITLE
Logging error while closing connection

### ISSUE THREAD

**Issue by Uranium2** [databricks/databricks-sql-python#168] opened 2023-07-05 07:28 UTC
Hello, I am using `databricks-sql-connector==2.7.0` 

I have an error regarding my logger (file) while exiting my script.

> 2023-07-04 18:25:36,806 - client - Successfully opened session 01ee1a87-684a-156f-add7-795029623668
Exception ignored in: <function Connection.__del__ at 0x7f1543b17820>
Traceback (most recent call last):
  File "/mypath/.venv/lib/python3.8/site-packages/databricks/sql/client.py", line 209, in __del__
  File "/mypath/.venv/lib/python3.8/site-packages/databricks/sql/client.py", line 251, in _close
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
NameError: name 'open' is not defined

This is just opening a databricks sql connection, and then make an exit. There is no error code:

```bash
$ echo $?
0
```

How can I avoid this tracecall at the exit of my script?

**Comment by susodapop** [comment] 2023-07-05 13:18
Thanks for this report. I'm investigating right now.

**Comment by Uranium2** [comment] 2023-07-05 15:14
Here is a minimal code that reproduce my error.

```python
import logging
import os
from datetime import datetime
from pathlib import Path

log_file_name = "test"
log_dir = "logs"
log_level = "INFO"

if not os.path.exists(log_dir):
    os.mkdir(log_dir)

base = Path(log_file_name).stem
extension = Path(log_file_name).suffix

log_file_path = os.path.join(
    log_dir,
    datetime.now().strftime(base + "_%Y_%m_%d_%H_%M_%S" + extension),
)

# Root Logger -> Will disable all loggers called after this
logger = logging.getLogger()
logger.setLevel(log_level)

# Set File Logger
file_handler = logging.FileHandler(log_file_path)
file_handler.setLevel(log_level)

# Stream handler
stream_handler = logging.StreamHandler()
stream_handler.setLevel(log_level)

# Formatter
formatter = logging.Formatter("%(asctime)s - %(module)s - %(message)s")
file_handler.setFormatter(formatter)
stream_handler.setFormatter(formatter)

logger.addHandler(file_handler)
logger.addHandler(stream_handler)


################

logging.info("testing")
from databricks import sql as dbsql

connection = dbsql.connect(
        server_hostname="your databricks server url",
        http_path="/sql/1.0/warehouses/xxxxxxxxx",
        access_token="dapi************************",
    )
with connection.cursor() as cursor:
    cursor.execute("Select 1")
    result = cursor.fetchall()

logging.info(result)
```

That will output me:
> 2023-07-05 17:11:04,087 - test_sql_logger - testing
2023-07-05 17:11:05,995 - client - Successfully opened session 01ee1b46-29e5-1464-a820-6f2e72cf1e08
2023-07-05 17:11:08,308 - test_sql_logger - [Row(1=1)]
Exception ignored in: <function Connection.__del__ at 0x7f80dc9ab3a0>
Traceback (most recent call last):
  File "/mypath/.venv/lib/python3.8/site-packages/databricks/sql/client.py", line 209, in __del__
  File "mypath/.venv/lib/python3.8/site-packages/databricks/sql/client.py", line 251, in _close
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
NameError: name 'open' is not defined

**Comment by Uranium2** [comment] 2023-07-05 15:47
An other information, when running my pytests in my project, I do not see this Traceback, Maybe due that pytests spawns threads or processes and they don't catch the Traceback. So this "error" is not showned when running any CI tools that tests the code. And even if it would, it does return an exit code 0.

**Comment by susodapop** [comment] 2023-07-11 01:45
Following up on this. I appreciate the reproduction steps. I'm running your exact script locally with version 2.7.0. I tested on Python 3.11.x and on Python 3.8.x

I'm confident this is not a bug in our connector.

It looks like you're using the system Python and moreover the error is not being raised by databricks-sql-connector but by your standard library `logging` module. We recommend running databricks-sql-connector within a dedicated virtual environment to isolate execution from side-effects caused by other installations. Please try that.

I'm closing your issue for now but feel free to reopen if the issue persists.

**Closed by susodapop** 2023-07-11 01:45 UTC

**Comment by Uranium2** [comment] 2023-07-11 07:53
This is very strange, because in local I am always using venv with python 3.8 `python -m venv .venv` and `source .venv/bin/activate`. I never code without venvs.

More over, we also have this inside Azure Machine Learning Computer Instances with the default docker image. And Computes clusters with the custom Dockerfile (but only openJDK 19 installed):

```
dockerfile = rf"""
        FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest

        RUN mkdir -p /usr/share/man/man1

        RUN apt-get -y update \
        && apt-get install  openjdk-19-jdk -y \
        && rm -rf /var/lib/apt/lists/*
        """
```

So this feels odd that you cannot reproduce this, because all our departement at the company that uses `databricks-sql-connector==2.7.0` have this symptoms. Most of them work with Computes instances in Azure Machine Learning, and other in local (WLS1).

I did more testings with the versions, and the issue are only for the version 2.6.0 and above. For the version 2.5.2 I do not have this issue.

For me it's linked to this change (src/databricks/sql/client.py, line 251 ):
![image](https://github.com/databricks/databricks-sql-python/assets/6902440/e77b8aa4-040e-430e-bb00-abe228966a0f)

I think that at this time of the code, when we delete the object by quitting the script, the logger calls `__del__` before the `__del__` of the Databricks's client. Thus will make the line 251 `logger.info(f"Closing session {self.get_session_id_hex()}")` fail this there are no loggers.

In the code from the tag 2.5.2 there is no logging in the `_close` method:

```python
    def _close(self, close_cursors=True) -> None:
        if close_cursors:
            for cursor in self._cursors:
                cursor.close()
        self.thrift_backend.close_session(self._session_handle)
        self.open = False
```
So I tested to close the connexion juste before exiting the script, and indeed it removes the logging error.

```python
import logging
import os
from datetime import datetime
from pathlib import Path

log_file_name = "test.log"
log_dir = "logs"
log_level = "INFO"

if not os.path.exists(log_dir):
    os.mkdir(log_dir)

base = Path(log_file_name).stem
extension = Path(log_file_name).suffix

log_file_path = os.path.join(
    log_dir,
    datetime.now().strftime(base + "_%Y_%m_%d_%H_%M_%S" + extension),
)

# Root Logger -> Will disable all loggers called after this
logger = logging.getLogger()
logger.setLevel(log_level)

# Set File Logger
file_handler = logging.FileHandler(log_file_path)
file_handler.setLevel(log_level)

# Stream handler
stream_handler = logging.StreamHandler()
stream_handler.setLevel(log_level)

# Formatter
formatter = logging.Formatter("%(asctime)s - %(module)s - %(message)s")
file_handler.setFormatter(formatter)
stream_handler.setFormatter(formatter)

logger.addHandler(file_handler)
logger.addHandler(stream_handler)


################

logging.info("testing")
from databricks import sql as dbsql

connection = dbsql.connect(
        server_hostname="your databricks server url",
        http_path="/sql/1.0/warehouses/xxxxxxxxx",
        access_token="dapi************************",
    )
with connection.cursor() as cursor:
    cursor.execute("Select 1")
    result = cursor.fetchall()

connection.close()

logging.info(result)
```

> 2023-07-11 09:50:05,117 - logging_tests - testing
2023-07-11 09:50:06,198 - client - Successfully opened session b'\x01\xee\x1f\xbf\x8d\x19\x18\xe5\x97\xb4\x96\xa4c6\xb9\xe4'
2023-07-11 09:50:06,613 - logging_tests - [Row(1=1)]

So maybe it's just a "timing" issue, or I should always close the connexion before the natural `__del__` of the `databricks.sql.client.Connection` object. But it still feels odds that the users must manually close the connexion.

**Comment by Uranium2** [comment] 2023-07-31 09:32
Issue seems to be resolved with this changes you made: https://github.com/databricks/databricks-sql-python/commit/8d70f6c046feda90402c713c8e47125da36ba55a
