### ISSUE TITLE
databricks.sql.exc.RequestError: Error during request to server

### ISSUE THREAD

**Issue by PaulCornellDB** [databricks/databricks-sql-python#23] opened 2022-07-25 21:51 UTC
Repro steps:

1. `pipenv --python 3.8`
2. `pipenv shell`
3. `pip install databricks-sql-connector`
4. `export DATABRICKS_SERVER_HOSTNAME="https://<redacted>.cloud.databricks.com" && export DATABRICKS_HTTP_PATH="sql/protocolv1/o/<redacted>/<redacted>" && export DATABRICKS_TOKEN="dapi<redacted>"`
5. Code (`main.py`):

```
from databricks import sql
import os

with sql.connect(server_hostname = os.getenv("DATABRICKS_SERVER_HOSTNAME"),
                 http_path       = os.getenv("DATABRICKS_HTTP_PATH"),
                 access_token    = os.getenv("DATABRICKS_TOKEN")) as connection:

  with connection.cursor() as cursor:
    cursor.execute("SELECT * FROM default.diamonds LIMIT 2")
    result = cursor.fetchall()

    for row in result:
      print(row)
```

6. `python main.py`
7. Traceback:

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    with sql.connect(server_hostname = os.getenv("DATABRICKS_SERVER_HOSTNAME"),
  File "/Users/paul.cornell/.local/share/virtualenvs/paul.cornell-<redacted>/lib/python3.8/site-packages/databricks/sql/__init__.py", line 48, in connect
    return Connection(server_hostname, http_path, access_token, **kwargs)
  File "/Users/paul.cornell/.local/share/virtualenvs/paul.cornell-<redacted>/lib/python3.8/site-packages/databricks/sql/client.py", line 112, in __init__
    self._session_handle = self.thrift_backend.open_session(session_configuration, catalog,
  File "/Users/paul.cornell/.local/share/virtualenvs/paul.cornell-<redacted>/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 341, in open_session
    response = self.make_request(self._client.OpenSession, open_session_req)
  File "/Users/paul.cornell/.local/share/virtualenvs/paul.cornell-<redacted>/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 287, in make_request
    self._handle_request_error(error_info, attempt, elapsed)
  File "/Users/paul.cornell/.local/share/virtualenvs/paul.cornell-<redacted>/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 199, in _handle_request_error
    raise network_request_error
databricks.sql.exc.RequestError: Error during request to server
```

8. Tried `export CERT_PATH=$(python -m certifi) && export SSL_CERT_FILE=${CERT_PATH} && export REQUESTS_CA_BUNDLE=${CERT_PATH}` and `python main.py` again, but same traceback.

Environment:

- Python 3.8.10
- `pip list`:

Package                  Version
certifi                  2022.6.15
databricks-sql-connector 2.0.2
numpy                    1.23.0
pandas                   1.4.3
pip                      21.0.1
pyarrow                  8.0.0
python-dateutil          2.8.2
pytz                     2022.1
setuptools               54.1.2
six                      1.16.0
thrift                   0.16.0
wheel                    0.36.2

**Comment by zhangzuolin16** [comment] 2022-10-31 07:09
dears, 

is there any solution to fix this issue?

**Comment by susodapop** [comment] 2022-11-14 21:05
As yet I'm not able to reproduce this behaviour in the connector. Even with this specified version of Python. My best recommendation is to try with a fresh installation of Python within a virtual environment.

**Comment by timon-schmelzer-gcx** [comment] 2022-11-15 10:36
I see the same behavior since a few weeks. Before that, everything was fine and a connection could be established. Nothing changed in the code / the SQL endpoint (at least not from my side). Just updated databricks-sql-connector to 2.1.0 but the result is the same.

**Comment by timon-schmelzer-gcx** [comment] 2022-11-15 10:46
...actually updating to 2.1.0 helped solving my issue! The error message changed from:
```
databricks.sql.thrift_backend: Error during request to server: {...}
```
to:
```
databricks.sql.thrift_backend: Error during request to server: : Invalid access token. {...}
```
So my databricks access token has been expired. After adding a new token to my script everything is running again 👍

**Comment by Uranium2** [comment] 2023-03-15 11:28
I am having the same issue.

In my case I was in databricks-sql-connector==2.4.0, then I tried to downgrade to 2.1.0, still the same message.

I have a proxy http and https environnement variable and a no_proxy.

no_proxy=localhost,my-company.com,my-company.net,10.0.0.0/8,documents.azure.com,dfs.core.windows.net,azuredatabricks.net,vault.azure.net,dfs.core.windows.net,file.core.windows.net,blob.core.windows.net
https_proxy=http://proxy.my-company.net:8080
http_proxy=http://proxy.my-company.net:8080

**Comment by susodapop** [comment] 2023-07-11 02:17
I'm closing this issue out due to its age. Feel free to reopen or make a new issue if a similar issue arrises.

**Closed by susodapop** 2023-07-11 02:17 UTC

**Comment by chozillla** [comment] 2023-09-24 11:27
The issue still exists. I had success with an initial access token, but I am getting RequestError: Error during request to server: : Invalid access token. when I used a new token and revoked the old one.

**Comment by susodapop** [comment] 2023-09-24 17:33
@chozillla Can you provide reproduction steps?

**Comment by chozillla** [comment] 2023-09-24 18:32
@susodapop `# Configure your table and database names in Databricks
DB_NAME = "bronze_aupe"
TABLE_NAME = "df_aupe_global"
load_dotenv()

# Set these as environment variables in Dash Enterprise or locally
SERVER_HOSTNAME = os.getenv("SERVER_HOSTNAME")
HTTP_PATH = os.getenv("HTTP_PATH")
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")


connection = sql.connect(
    server_hostname = SERVER_HOSTNAME,
                        http_path = HTTP_PATH,
                        access_token = ACCESS_TOKEN)

# Query to fetch all data from the DataFrame
# Before executing the query
query = f"SELECT * FROM {DB_NAME}.{TABLE_NAME}"
cursor = connection.cursor()
cursor.execute(query)
df_pd_global = cursor.fetchall_arrow().to_pandas()
cursor.close()` Interestingly, it works fine when I explicitly put in the values. This is on a jupyter notebook on vscode via Anaconda.

**Comment by chozillla** [comment] 2023-09-24 19:20
Uh, so I just exited vscode and restarted and it worked. Strange issue. 
<img width="750" alt="Screenshot 2023-09-24 at 9 19 51 PM" src="https://github.com/databricks/databricks-sql-python/assets/29260819/12cb4ca5-5450-43f9-84ba-2f51610480fc">

**Comment by vcakdwivedi** [comment] 2024-01-26 06:29
Hi Everyone,
Is there any fix for above issue? I tried everything mentioned above.
main(server_hostname = args.server_hostname, http_path = args.http_path, schema = args.schema, access_token = args.access_token)
  File "extract.py", line 24, in main
    dbx_extractor.execute_sql(sql_query, server_hostname, http_path, access_token)
  File "/mnt/azureml/cr/j/2c91464c9e0743f5860e8f48b407683d/exe/wd/dbextractor.py", line 23, in execute_sql
    with db_sql.connect(
  File "/azureml-envs/azureml_9806bfc7c716eaf0df12bea8512e961b/lib/python3.8/site-packages/databricks/sql/__init__.py", line 50, in connect
    return Connection(server_hostname, http_path, access_token, **kwargs)
  File "/azureml-envs/azureml_9806bfc7c716eaf0df12bea8512e961b/lib/python3.8/site-packages/databricks/sql/client.py", line 189, in __init__
    self._session_handle = self.thrift_backend.open_session(
  File "/azureml-envs/azureml_9806bfc7c716eaf0df12bea8512e961b/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 464, in open_session
    response = self.make_request(self._client.OpenSession, open_session_req)
  File "/azureml-envs/azureml_9806bfc7c716eaf0df12bea8512e961b/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 393, in make_request
    self._handle_request_error(error_info, attempt, elapsed)
  File "/azureml-envs/azureml_9806bfc7c716eaf0df12bea8512e961b/lib/python3.8/site-packages/databricks/sql/thrift_backend.py", line 261, in _handle_request_error
    raise network_request_error
databricks.sql.exc.RequestError: Error during request to server

**Comment by susodapop** [comment] 2024-01-26 06:33
Hi there, to investigate this we need reproduction steps. So far, every
instance of this issue that we've traced has been an environment issue
rather than a bug in the code. If you can provide reproduction steps we can
try to guide you toward the fix.

At the very least we need to know the exception text, since RequestError
can point in many different directions.

**Comment by Ownmarc** [comment] 2024-02-09 20:39
Hello,

We are seeing similar error, here is the relevant exception text. We use polars (0.20.6) to make requests to our Databricks endpoint using the client. This works fine for some time until it stops working. Then if we simply restart our pod (lives as a docker container in kubernetes), it starts working again.

```
def get_databricks_connection():
    return sql.connect(
        server_hostname=os.getenv("DATABRICKS_SERVER_HOSTNAME"),
        http_path=os.getenv("DATABRICKS_HTTP_PATH"),
        access_token=os.getenv("DATABRICKS_TOKEN"),
        use_inline_params=True,
    )

databricks_connection = get_databricks_connection()

pl.read_database(
            query=QUERY,
            connection=databricks_connection,
            execute_options={
                "parameters": {
                    "some_param": some_param,
                }
            },
        )
```



`line 255, in _query_event\n return pl.read_database(\n File \"/home/python/.local/lib/python3.10/site-packages/polars/io/database.py\", line 582, in read_database\n return cx.execute(\n File \"/home/python/.local/lib/python3.10/site-packages/polars/io/database.py\", line 345, in execute\n result = cursor_execute(query, **options)\n File \"/home/python/.local/lib/python3.10/site-packages/databricks/sql/client.py\", line 761, in execute\n execute_response = self.thrift_backend.execute_command(\n File \"/home/python/.local/lib/python3.10/site-packages/databricks/sql/thrift_backend.py\", line 868, in execute_command\n resp = self.make_request(self._client.ExecuteStatement, req)\n File \"/home/python/.local/lib/python3.10/site-packages/databricks/sql/thrift_backend.py\", line 507, in make_request\n self._handle_request_error(error_info, attempt, elapsed)\n File \"/home/python/.local/lib/python3.10/site-packages/databricks/sql/thrift_backend.py\", line 337, in _handle_request_error\n raise network_request_error\ndatabricks.sql.exc.RequestError: Error during request to server"`

**Comment by sfc-gh-smao** [comment] 2024-03-06 18:40
Hello, I'm seeing the same error.

Code:

```
from databricks import sql
import os

with sql.connect(
    server_hostname="****************.cloud.databricks.com",
    http_path="/sql/1.0/warehouses/****************",
    access_token="****************",
) as connection:
    cursor = connection.cursor()

    cursor.execute("SELECT * from range(10)")
    print(cursor.fetchall())

    cursor.close()
    connection.close()
```

Error:

```
   with sql.connect(
         ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/databricks/sql/__init__.py", line 84, in connect
    return Connection(server_hostname, http_path, access_token, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/databricks/sql/client.py", line 232, in __init__
    self._open_session_resp = self.thrift_backend.open_session(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/databricks/sql/thrift_backend.py", line 578, in open_session
    response = self.make_request(self._client.OpenSession, open_session_req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/databricks/sql/thrift_backend.py", line 507, in make_request
    self._handle_request_error(error_info, attempt, elapsed)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/databricks/sql/thrift_backend.py", line 337, in _handle_request_error
    raise network_request_error
databricks.sql.exc.RequestError: Error during request to server
```

**Comment by sfc-gh-smao** [comment] 2024-03-06 18:42
@susodapop  Can you please reopen this issue? There are new reports for this issue since the issue was closed.

**Comment by susodapop** [comment] 2024-03-06 21:38
I'm not able to reopen issues any longer. But I would encourage you to turn on DEBUG logging for your connector and share what you find. `RequestError` is a very generic exception and could point to any number of issues. Without more detail it's impossible to say what the root cause is.

**Comment by ANL06488** [comment] 2024-06-19 09:04
I am getting this same error, and when turning debug logging on I see:
```
Received 403 - FORBIDDEN. Confirm your authentication credentials.
```
But I'm not sure how to get past this. We're using a personal access token generated from SQL Warehouse connection API. Connecting with the same token works when running locally, but not from our production app.

**Comment by Jasonnicholas-ZEN** [comment] 2024-08-28 00:42
Hi, are there any updates on this? I am facing similar issue. Could it be because the Databricks cluster that it needs to use is inactive? Could it be the source of the issue of `databricks.sql.exc.RequestError: Error during request to server`

**Comment by sebastianfastert** [comment] 2024-09-09 07:49
@Ownmarc did you find a solution?

I have a similar situation, where the deployment stops working after a while.

**Comment by Ownmarc** [comment] 2024-09-09 10:31
> @Ownmarc did you find a solution?
> 
> I have a similar situation, where the deployment stops working after a while.

Open and close connection, don’t keep them open for a while will solve it. This takes almost no time, what will take time is the coldstarts on your Databricks cluster side, but on e its up, creating a new connection takes no time.

**Comment by susodapop** [comment] 2024-09-09 12:11
That sounds accurate to me @Ownmarc. As database users, I think we are all inclined to keep connections open for long periods of time because connections / sessions are _cheap_ on most databases. But on Databricks, sessions are expensive and are periodically closed down for inactivity as a cost-savings measure.

To get around this, you can either implement a heartbeat to keep the session alive (incurring cost from the cluster remaining online), or implement some logic that catches the exception when you attempt an operation on a closed session and opens a new one.

The downside of this latter approach is that if you have set a bunch of session variables on your session, you'll need to set them again on the new session if the first one expires.

**Comment by Haopeng138** [comment] 2025-01-16 12:31
In my case, my PAT token had expired. Once I generated a new token, it works.

**Comment by kylebeni** [comment] 2026-01-07 17:07
In my case, the token was valid but the http path pointed to a warehouse that the user (service principal, in this case) did not have access to.

So:
1. ensure the token is valid
2. ensure the user who generated the token has permission to connect to the warehouse
