### ISSUE TITLE
UNBOUND_SQL_PARAMETER when running the example with 14.2

### ISSUE THREAD

**Issue by Falydoor** [databricks/databricks-sql-python#288] opened 2023-11-21 16:15 UTC
Hello,

When running the example from the doc:
```python
from databricks import sql

connection = sql.connect(
  server_hostname=HOSTNAME,
  http_path=HTTP_PATH,
  access_token=TOKEN)

cursor = connection.cursor()
cursor.execute('SELECT :param `p`, * FROM RANGE(10)', {"param": "foo"})
result = cursor.fetchall()
for row in result:
  print(row)

cursor.close()
connection.close()
```

I'm getting this error:
```
Traceback (most recent call last):
  File "/Users/theo/Documents/perso/dbx/main.py", line 34, in <module>
    cursor.execute('SELECT :param `p`, * FROM RANGE(10)', {"param": "foo"})
  File "/Users/theo/Documents/perso/dbx/.env/lib/python3.11/site-packages/databricks/sql/client.py", line 761, in execute
    execute_response = self.thrift_backend.execute_command(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theo/Documents/perso/dbx/.env/lib/python3.11/site-packages/databricks/sql/thrift_backend.py", line 867, in execute_command
    return self._handle_execute_response(resp, cursor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theo/Documents/perso/dbx/.env/lib/python3.11/site-packages/databricks/sql/thrift_backend.py", line 959, in _handle_execute_response
    final_operation_state = self._wait_until_command_done(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theo/Documents/perso/dbx/.env/lib/python3.11/site-packages/databricks/sql/thrift_backend.py", line 792, in _wait_until_command_done
    self._check_command_not_in_error_or_closed_state(
  File "/Users/theo/Documents/perso/dbx/.env/lib/python3.11/site-packages/databricks/sql/thrift_backend.py", line 596, in _check_command_not_in_error_or_closed_state
    raise ServerOperationError(
databricks.sql.exc.ServerOperationError: [UNBOUND_SQL_PARAMETER] Found the unbound parameter: param. Please, fix `args` and provide a mapping of the parameter to either a SQL literal or collection constructor functions such as `map()`, `array()`, `struct()`. SQLSTATE: 42P02; line 1 pos 7
```

It looks like the native query parameter isn't working correctly. I'm using an all purpose cluster with a runtime of `14.2` with photon acceleration disabled.

Thank you!

**Comment by susodapop** [comment] 2023-11-21 17:49
Thanks for this report. I'm trying to reproduce right now.

**Comment by susodapop** [comment] 2023-11-21 18:10
I've reproduced the same issue internally. Will follow-up with our internal engineers to figure out what's happening here since I'm using the latest 14.2 snapshot with an all-purpose cluster.

**Comment by susodapop** [comment] 2023-11-21 18:27
Just following up to say that this exact code snippet _does work_ when connected to a SQL warehouse with DBR 14.2

**Comment by vlasvlasvlas** [comment] 2023-11-21 18:31
thanks, same here! 
ill try with 14.2 beta

**Comment by vlasvlasvlas** [comment] 2023-11-21 19:00
I'm puzzled about why the parameter designed to help optimize the query, specifically the 'get the first n rows so I can check the data,' isn't functioning as intended. Any insights on this issue?

**Comment by susodapop** [comment] 2023-11-21 20:09
> I'm puzzled about why the parameter designed to help optimize the query, specifically the 'get the first n rows so I can check the data,' isn't functioning as intended. Any insights on this issue?

This looks like a question for the langchain repo. I don't have any insight about their codebase.

**Comment by nchammas** [comment] 2023-11-27 20:42
Until this issue is fixed for DBR 14.2 clusters, I suppose the workaround is to use [Inline Parameters][1], correct?

Is there a way to use those with SQLAchemy? The SQLAlchemy docs do describe [inlining parameters][2], but I'm not sure how to use that information alongside the parameter docs for this library here.

[1]: https://github.com/databricks/databricks-sql-python/blob/a1bb6f9d87188d084e5aeeb9f7d931e115308970/docs/parameters.md#using-inline-parameters

[2]: https://docs.sqlalchemy.org/en/20/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined

**Comment by Falydoor** [comment] 2023-11-28 04:30
@nchammas Try using a SQL warehouse instead, that sounds easier than using inline parameters.

**Comment by susodapop** [comment] 2023-11-28 15:16
@Falydoor is correct that using a sql warehouse for the time-being is the only true workaround at this time. I'm following up with the engineers about when this will be fixed on all-purpose clusters.

> Is there a way to use those with SQLAchemy? 

No, databricks-sql-connector's inline parameters are never supported with sqlalchemy (because sqlalchemy doesn't know how to write out the correct variable markers). As you found in the sqlalchemy docs, you can force sqlalchemy to write parameter values as strings in emitted queries - this uses a completely different code path from databricks-sql-connector's inline behaviour, though.

**Comment by CAholder** [comment] 2023-12-06 00:39
@nchammas What was your in line workaround? I'm facing the same issue here and need a workaround while the Databricks team fixes this. I cannot use SQL warehouse due to cost reasons

**Comment by vlasvlasvlas** [comment] 2023-12-06 13:16
> @nchammas What was your in line workaround? I'm facing the same issue here and need a workaround while the Databricks team fixes this. I cannot use SQL warehouse due to cost reasons

changing databricks cluster version to 14.2 beta made it for me.

**Comment by kravets-levko** [comment] 2024-04-17 17:38
Hi everyone in this thread! Can you please let me know if this issue is still relevant for any of you? Thank you so much!

**Comment by Falydoor** [comment] 2024-04-19 02:43
Hey @kravets-levko,

I just tried with a cluster using `DBR 15.0` with `databricks-sql-connector==3.1.1` and everything works fine 👍

**Closed** 2024-10-02 17:33 UTC
