### ISSUE TITLE
PyArrow version requirement

### ISSUE THREAD

**Issue by YS-L** [databricks/databricks-sql-python#55] opened 2022-10-05 08:53 UTC
Hello! Is the version requirement on the pyarrow package strict?
```
pyarrow = "^9.0.0"
````

We would like to use `databricks-sql-python` in a project that depends on a lower version of pyarrow (8.0.0). We ran into conflicting version issues when using package management tools such as poetry. In our tests it seems `databricks-sql-python` can work with older versions of pyarrow such as 8.0.0. It would be great if `databricks-sql-python` can specify a wider range of pyarrow versions for better compatibility.

**Comment by Tom-Newton** [comment] 2022-11-10 10:43
I have a similar issue but personally I'm interested in using pyarrow `10.0.0`. It would be great if this was allowed.

**Comment by susodapop** [comment] 2022-11-30 17:10
@Tom-Newton pyarrow `10.0.1` is now supported as our `v2.2.1` release.

@YS-L I'll look into reducing our pyarrow specificaiton. I think we landed on version 9 because it was the latest at the time we wrote the connector.

**Comment by Tom-Newton** [comment] 2022-12-08 21:40
Thanks @susodapop 🙂 . With 2.2.1 my pyarrow problem is solved but now numpy is an issue. We are on numpy `1.22.4` with python 3.8. Is there are reason that the numpy requirement needs to be so strict?

**Comment by susodapop** [comment] 2022-12-15 16:56
I want to make this work for you but I also can't reproduce your installation problem. For your info: note that our specific requirements were dictated by Poetry so we haven't deliberately excluded anyone and thus far our tests run automatically on Python 3.7-3.11 without issues.

You're welcome to open a pull request that modifies `pyproject.toml` and `poetry.lock` to meet your needs. As long as it passes our build checks I'm happy to merge it. But this isn't something we're prepared to do on our own because nothing is broken for us.

**Comment by Tom-Newton** [comment] 2022-12-31 13:20
I created a PR https://github.com/databricks/databricks-sql-python/pull/74. It needs a review and for someone to approve running the build checks.

**Comment by Tom-Newton** [comment] 2023-02-13 21:38
> I created a PR #74. It needs a review and for someone to approve running the build checks.

@susodapop please could you approve running the github workflows 
![image](https://user-images.githubusercontent.com/9131935/218580247-349e0821-f2d2-44b1-9460-7e6f63fe1aed.png)

**Comment by susodapop** [comment] 2023-02-13 22:16
Done!

**Closed** 2024-04-17 18:26 UTC
