### ISSUE TITLE
Pandas 2.0 support

### ISSUE THREAD

**Issue by nicholasarquette** [databricks/databricks-sql-python#102] opened 2023-04-13 15:36 UTC
Any idea when Pandas 2.0 will be supported? I just tried to install it in my virtual environment and there was a conflict with the databricks-sql-python package?

![image](https://user-images.githubusercontent.com/89653636/231811297-28547c41-4c14-416d-b892-f46eec4fa0b1.png)

**Comment by susodapop** [comment] 2023-04-16 21:12
This is a duplicate of #91. We'll discuss timelines for this and update that ticket within the next week.

**Comment by PedroBrochado** [comment] 2023-04-26 14:34
Hello @susodapop 👋 
Sorry to be that person....
Any idea when this will be on the roadmap?

**Comment by susodapop** [comment] 2023-04-26 14:37
Thanks for the ping. We'll have the answer today about the timeline.

**Comment by susodapop** [comment] 2023-04-27 18:10
After discussion with the team we've actually deprioritised this. We won't consider a timeline for it again for at least a few more weeks. I know that's not a great answer ☹️  It's a side-effect of a lot of things in the pipeline for both this connector and  dbt-databricks (its biggest user).

Perhaps you can help with this? Long-term we'd like to remove the pandas dependency from the connector entirely. Short-term, do you think it would be acceptable to simply update `pyproject.toml` to allow `pandas==^2.0.0`? If so, we would absolutely review a pull request implementing such a change. If it passes our test suite then there's little risk.

This wouldn't work if pandas 2.0 support involves significant syntax changes to the few places where we `import pandas as pd` and do something with it.

**Comment by PedroBrochado** [comment] 2023-04-27 19:24
@susodapop I had a quick attempt on it, all unit tests pass with `pandas@^2.0.0` (it works on my machine 😅). 
But I had to update the python version to `>=3.8.0`. Is this acceptable?

**Comment by PedroBrochado** [comment] 2023-05-03 12:03
@susodapop Any thoughts on my comment above about `python >=3.8.0`

**Comment by susodapop** [comment] 2023-05-05 16:26
Dropping support for Python 3.7 is a significant decision that we need to adequately consider how it will affect other users. I wonder if Poetry will allow us to specify an older version of pandas for Python 3.7 and a newer version of Pandas for >3.8?

**Comment by cdcadman** [comment] 2023-05-23 01:33
@PedroBrochado @susodapop, I think either of these approaches would work:

- pandas = ">=1.2.5": https://github.com/cdcadman/databricks-sql-python/commit/5d37969fe5f1adbeb6c925286630ae4b4312173a
- pandas = [
    {version = "^2.0.0", python = ">=3.8"},
    {version = "^1.2.5", python = "<3.8"}
]: https://github.com/cdcadman/databricks-sql-python/commit/11c07989451425ba5fbeaface6f3bf5c752b3a46

**Comment by arkeodev** [comment] 2023-06-03 21:47
Is there any update for pandas 2.0 support? Thank you

**Comment by bouillon** [comment] 2023-07-25 14:05
Any plans to release it?

**Comment by susodapop** [comment] 2023-07-25 17:58
We released version 2.8.0 which allows installation alongside pandas==2.0

https://github.com/databricks/databricks-sql-python/releases/tag/v2.8.0

**Closed by susodapop** 2023-07-25 17:58 UTC
