### ISSUE TITLE
Python 3.12 incompatible? - requirements need update

### ISSUE THREAD

**Issue by bondyr3** [databricks/databricks-sql-python#334] opened 2024-01-26 17:29 UTC
python= 3.12.1
databricks-sql-connector==2.9.3
Windows

Per [https://docs.databricks.com/en/dev-tools/python-sql-connector.html](https://docs.databricks.com/en/dev-tools/python-sql-connector.html),

Databricks SQL Connector for Python Requirements:
A development machine running Python >=3.8 and <=3.11.

thrift hangs on import ttypes
or
```
  File "<env>\Lib\site-packages\databricks\sql\client.py", line 670, in fetchall
    return self.active_result_set.fetchall()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<env>\Lib\site-packages\databricks\sql\client.py", line 944, in fetchall
    return self._convert_arrow_table(self.fetchall_arrow())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<env>\Lib\site-packages\databricks\sql\client.py", line 884, in _convert_arrow_table  
    res = df.to_numpy(na_value=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<env>\Lib\site-packages\pandas\core\frame.py", line 1981, in to_numpy
    result = self._mgr.as_array(dtype=dtype, copy=copy, na_value=na_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<env>\Lib\site-packages\pandas\core\internals\managers.py", line 1702, in as_array    
    arr[isna(arr)] = na_value
    ~~~^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

```

**Comment by susodapop** [comment] 2024-01-26 21:11
This is a duplicate of https://github.com/databricks/databricks-sql-python/issues/326

You can workaround it by downgrading your local `pandas` installation to `pandas==2.0.1`.

Python 3.12 isn't the problem.

**Closed** 2024-01-26 21:12 UTC
