### ISSUE TITLE
Errors during connection close when using sqlalchemy

### ISSUE THREAD

**Issue by sebbegg** [databricks/databricks-sql-python#157] opened 2023-06-23 11:00 UTC
Hi there,

when using databricks-sql-python along with sqlalchemy I noticed that apparently the connection is not properly? closed when using contexts.
This suffices to reproduce the issue in my environment:

```python
  from sqlalchemy import create_engine, text

  host = os.environ["DATABRICKS_SQL_HOST"]
  token = os.environ["DATABRICKS_SQL_TOKEN"]
  path = os.environ["DATABRICKS_SQL_PATH"]
  database = os.environ["DATABRICKS_SQL_DATABASE"]


  engine = create_engine(
      f"databricks://token:{token}@{host}?http_path={path}&schema={database}",
  )

  with engine.begin() as conn:
      for row in conn.execute(text("SELECT 1 as value")):
          print(row)

  print("Context cleared")
```

Which produces the following logs:

```console
023-06-23 12:51:45.150 databricks.sql.thrift_backend DEBUG   :: retry parameter: _retry_delay_min given_or_default 1.0
2023-06-23 12:51:45.150 databricks.sql.thrift_backend DEBUG   :: retry parameter: _retry_delay_max given_or_default 60.0
2023-06-23 12:51:45.150 databricks.sql.thrift_backend DEBUG   :: retry parameter: _retry_stop_after_attempts_count given_or_default 30
2023-06-23 12:51:45.150 databricks.sql.thrift_backend DEBUG   :: retry parameter: _retry_stop_after_attempts_duration given_or_default 900.0
2023-06-23 12:51:45.150 databricks.sql.thrift_backend DEBUG   :: retry parameter: _retry_delay_default given_or_default 5.0
2023-06-23 12:51:45.164 databricks.sql.thrift_backend DEBUG   :: Sending request: TOpenSessionReq...
2023-06-23 12:51:45.592 databricks.sql.thrift_backend DEBUG   :: Received response: TOpenSessionResp...
2023-06-23 12:51:45.592 databricks.sql.client INFO    :: Successfully opened session ...
2023-06-23 12:51:45.593 databricks.sql.thrift_backend DEBUG   :: Sending request: TExecuteStatementReq...
2023-06-23 12:51:45.705 databricks.sql.thrift_backend DEBUG   :: Received response: TExecuteStatementResp ...
(1,)
Context cleared
2023-06-23 12:51:45.812 databricks.sql.client DEBUG   :: Closing unclosed connection for session ...
2023-06-23 12:51:45.812 databricks.sql.thrift_backend DEBUG   :: Sending request: TCloseSessionReq(sessionHandle=TSessionHandle(sessionId=THandleIdentifier(guid=..., secret=..., executionVersion=None), serverProtocolVersion=42246))
2023-06-23 12:51:45.813 urllib3.connectionpool WARNING :: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(0, 'Underlying socket connection gone (_ssl.c:2407)'))': <http-path>
2023-06-23 12:51:45.843 databricks.sql.thrift_backend INFO    :: Error during request to server: {"method": "CloseSession", "session-id": ..., "query-id": null, "http-code": 200, "error-message": "", "original-exception": "sys.meta_path is None, Python is likely shutting down", "no-retry-reason": "non-retryable error", "bounded-retry-delay": null, "attempt": "1/30", "elapsed-seconds": "0.030328989028930664/900.0"}
2023-06-23 12:51:45.843 databricks.sql.client DEBUG   :: Couldn't close unclosed connection: Error during request to server
```

This is using:
* python 3.9.16
* SQLAlchemy==1.4.48
* databricks-sql-connector==2.6.2

Is that supposed to be supported? Anything I might be doing wrong?

It's not actually causing an uncaught exception though.

**Comment by susodapop** [comment] 2023-06-23 23:51
Thanks for this report. I'm not able to reproduce this locally. The error is a strange one:

```
Underlying socket connection gone (_ssl.c:2407)
```

and

```
sys.meta_path is None, Python is likely shutting down
```

To check if this is a regression, can you try this same script using databricks-sql-connector==2.5.2?

**Comment by sebbegg** [comment] 2023-06-26 07:58
Looks like it is, with 2.5.2 I just get:

```console
2023-06-26 09:57:23.829 databricks.sql.client DEBUG   :: Closing unclosed connection for session ...
2023-06-26 09:57:23.829 databricks.sql.thrift_backend DEBUG   :: Sending request: TCloseSessionReq(...
2023-06-26 09:57:24.027 databricks.sql.thrift_backend DEBUG   :: Received response: TCloseSessionResp(status=TStatus(statusCode=0, infoMessages=None, sqlState=None, errorCode=None, errorMessage=None, displayMessage=None, responseValidation=None))
```

**Comment by susodapop** [comment] 2023-06-30 12:25
Thanks! Can you try with version `databricks-sql-connector==2.7.0` which we just released? This version gives us more visibility into the failure if it persists, as we have modified the logging around this behaviour.

**Comment by susodapop** [comment] 2023-07-11 01:53
I've given this another whirl across multiple versions of Python and of our connector. I still can't reproduce it. I'm closing this issue for now but feel free to reopen if the issue persists.

**Closed by susodapop** 2023-07-11 01:53 UTC

**Comment by sebbegg** [comment] 2023-07-27 13:38
It's been a while, but I went ahead and tested with an up to date version:

`databricks-sql-test.py`
```python
import logging
import os

import dotenv
import sqlalchemy

if __name__ == "__main__":

    dotenv.load_dotenv()

    logging.basicConfig(
        format="%(asctime)s.%(msecs)03d %(name)-18s %(levelname)-8s:: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        level="INFO",
    )
    logging.getLogger("databricks.sql").setLevel("DEBUG")

    engine = sqlalchemy.create_engine(
        "databricks://",
        connect_args={
            "server_hostname": os.environ["DATABRICKS_SQL_HOST"],
            "access_token": os.environ["DATABRICKS_SQL_TOKEN"],
            "http_path": os.environ["DATABRICKS_SQL_PATH"],
        },
    )

    with engine.connect() as conn:
        conn.execute("SELECT 1")
```

Just to ensure it's not a local OS issue, I tried with a Dockerfile:

```Dockerfile
FROM python:3.10-slim

RUN pip install -U pip && pip install databricks-sql-connector==2.8.0 sqlalchemy==1.4.49 python-dotenv

WORKDIR /test
COPY ./databricks-sql-test.py /test/

CMD ["python", "databricks-sql-test.py"]
```

Still, this produces:
```console
...
023-07-27 13:31:40.803 databricks.sql.thrift_backend INFO    :: Error during request to server: {"method": "CloseSession", "session-id": "b';\\xd6-\\x03\\xed\\x87Ja\\x89\\xdf;\\xe23D\\xa9?'", "query-id": null, "http-code": 200, "error-message": "", "original-exception": "sys.meta_path is None, Python is likely shutting down", "no-retry-reason": "non-retryable error", "bounded-retry-delay": null, "attempt": "1/30", "elapsed-seconds": "0.03797483444213867/900.0"}
...
```
